In [1]:
# Q1 1~20等差級數
import numpy as np
seq = np.arange(0, 21, step=1)
print(seq)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
# Q2 判斷是偶數
even_seq = np.array([i for i in seq if i%2==0])
print(even_seq)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [3]:
# Q3 判斷是三的倍數（包括0
three_seq = np.array([i for i in seq if i%3==0])
print(three_seq)

[ 0  3  6  9 12 15 18]
